export const ICONS = {
  SEARCH: "/icons/input-prefix.svg",
  BELL: "/icons/bell.svg",
  HEART: "/icons/heart.svg",
  HOME: "/icons/nav-home.svg",
  CART: "/icons/nav-cart.svg",
  ORDERS: "/icons/nav-orders.svg",
  WALLET: "/icons/nav-wallet.svg",
  PROFILE: "/icons/nav-profile.svg",
  EYE: "/icons/eye-svgrepo-com.svg",
  EYE_SLASH: "/icons/eye-slash-fill-svgrepo-com.svg",
  LOGO: "/icons/Vector 1.png",
  EMAIL: "/icons/email-14-svgrepo-com.svg",
  LOCK: "/icons/lock-svgrepo-com.svg",
  HAND_EMOJI: "/images/👋.png",
};
