export const ICONS = {
  SEARCH: "/icons/input-prefix.svg",
  BELL: "/icons/bell.svg",
  HEART: "/icons/heart.svg",
  HOME: "/icons/home.svg",
  CART: "/icons/cart.svg",
  ORDERS: "/icons/orders.svg",
  WALLET: "/icons/wallet.svg",
  PROFILE: "/icons/profile.svg",
  EYE: "/icons/eye-svgrepo-com.svg",
  EYE_SLASH: "/icons/eye-slash-fill-svgrepo-com.svg",
  LOGO: "/icons/Vector 1.png",
  EMAIL: "/icons/email-14-svgrepo-com.svg",
  LOCK: "/icons/lock-svgrepo-com.svg",
  HAND_EMOJI: "/images/👋.png",
  STAR: "/icons/star-sharp-svgrepo-com.svg",
};
